config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get '/new', to: 'users#new', as: 'new_user'
  post '/create', to: 'users#create', as: 'create_user'
  get '/contact', to: 'static_pages#contact', as: 'contact'
  get '/about', to: 'static_pages#about', as: 'about'
  get '/users/(:id)', to: 'users#show', as: 'show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @random_number =rand(1000)
    puts "random number home: #{@random_number}"
  end

  def contact
    @random_number =rand(1000)
    puts "random number contact: #{@random_number}"
  end

  def about
    @random_number =rand(1000)
    puts "random number about: #{@random_number}"
  end

  def about_user
    @random_number =rand(1000)
    puts "random number about_user: #{@random_number}"
  end

  def about_group
    @random_number =rand(1000)
    puts "random number about_group: #{@random_number}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@random_number = rand(2000)
  	puts "random_number = #{@random_number}"
    puts "on affiche depuis def new"
  end

  def create
    puts params.inspect
    puts "Token: #{params[:authenticity_token]}"
    @user = User.create(username: params[:username], bio:params[:bio])
    if @user.save
      redirect_to action: 'show', id: @user.username
      else render '/users/errors'
    end

    puts @user.username
    puts "on affiche depuis create"
  end


  def show
    puts Time.now
    puts "j'affiche depuis show"
    puts "numéro de l'id #{params[:id].to_i}"
    @user = User.find_by(params[:username])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_controller_helper.rb
module UsersControllerHelper
end

app/helpers/users_cotroller_helper.rb
module UsersCotrollerHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JeMePresente</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"/>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="<%= root_path %>">My new app</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= show_path %>">My profil<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= contact_path %>">contact</a>
      </li>
  </div>
</nav>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/static_pages/about.html.erb
h1>Bienvenue sur la page about: </h1>
<p>Pour accéder à ton, profil utilisateur, clique ici:</p>
<a href="<%= about_user_path %>">Acces utilsateur<a>

app/views/static_pages/about_my_group.html.erb
<h1>StaticPages#my_group</h1>
<p>Find me in app/views/static_pages/my_group.html.erb</p>

app/views/static_pages/about_user.html.erb
<<h1>StaticPages#user</h1>
<p>Find me in app/views/static_pages/user.html.erb</p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/home.html.erb
<h1>Bienvenue !</h1>
<p>Pour créer un utilisateur, cliquez <a href="<%=new_user_path%>"> Ici </a> </p>

app/views/users/errors.html.erb
<h1>  essaie encore</h1>

app/views/users/new.html.erb
<h1>Create your profile :</h1>


<form action="/create" method="post">
	name:<br>
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
	<input type="text" name="username"><br>
	bio:<br>
	<input type="text" name="bio"><br>
	<input type="submit" value="Submit">
</form>

app/views/users/show.html.erb
<h1>Bienvenue <%= @user.username %></h1>
<p>Voici ta bio: </p>
<p><%= @user.bio %></p>